// Generate a new character pack scaffold

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import type { CharacterYaml, VoiceYaml } from "./schema.js";

export interface GenerateOptions {
  /** Slug like "my-character". */
  id: string;
  /** Display name. */
  name: string;
  author?: string;
  avatarMode?: "live2d" | "vrm";
  description?: string;
  /** Parent directory, e.g. "characters". */
  outDir: string;
}

function escapeYamlString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function shouldQuoteString(value: string): boolean {
  if (value === "") return true;
  return (
    value.includes(":") ||
    value.includes("#") ||
    value.includes("\n") ||
    value.trim() !== value ||
    ["true", "false", "null"].includes(value.toLowerCase())
  );
}

function toYAMLValue(value: unknown, indent: number): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return String(value);
  if (typeof value === "string") {
    return shouldQuoteString(value) ? `"${escapeYamlString(value)}"` : value;
  }
  return `\n${toYAML(value, indent + 1)}`;
}

function toYAML(obj: unknown, indent = 0): string {
  const pad = "  ".repeat(indent);

  if (Array.isArray(obj)) {
    return obj.map((value) => `${pad}- ${toYAMLValue(value, indent)}`).join("\n");
  }

  if (obj !== null && typeof obj === "object") {
    return Object.entries(obj as Record<string, unknown>)
      .map(([key, value]) => `${pad}${key}: ${toYAMLValue(value, indent)}`)
      .join("\n");
  }

  return toYAMLValue(obj, indent);
}

function writeTextFile(path: string, content: string): void {
  writeFileSync(path, content, "utf8");
}

export function generatePack(opts: GenerateOptions): string {
  const {
    id,
    name,
    author = "Unknown",
    avatarMode = "vrm",
    description = "",
    outDir,
  } = opts;
  const packDir = join(outDir, id);

  if (existsSync(packDir)) {
    throw new Error(`Pack "${id}" already exists at ${packDir}`);
  }

  mkdirSync(packDir, { recursive: true });

  const characterYaml: CharacterYaml = {
    id,
    name,
    type: "manual",
    source: { kind: "local", consent: true },
    avatar: {
      default_mode: avatarMode,
      modes: {
        live2d: { enabled: false, model: "./live2d/model.model3.json" },
        vrm: { enabled: false, model: "./vrm/model.vrm" },
      },
    },
    persona: { file: "./persona.md" },
    voice: { file: "./voice.yaml" },
    states: {
      idle: { expression: "neutral", motion: "idle" },
      listening: { expression: "focused", motion: "listen" },
      thinking: { expression: "thinking", motion: "think" },
      speaking: { expression: "neutral", motion: "speak" },
      success: { expression: "happy", motion: "nod" },
      warning: { expression: "alert", motion: "alert" },
      error: { expression: "confused", motion: "confused" },
    },
  };

  writeTextFile(
    join(packDir, "character.yaml"),
    `# ${name}\n# Generated by NAIS on ${new Date().toISOString().split("T")[0]}\n# Author: ${author}\n# ${description}\n\n${toYAML(characterYaml)}\n`,
  );

  const persona = `# ${name}\n\n${
    description ? `${description}\n\n` : ""
  }## About\nWrite a brief description of this character here.\n\n## Personality\nDescribe the character's personality, mannerisms, and speaking style.\n\n## Notes\nAdd any additional notes about this character.\n`;
  writeTextFile(join(packDir, "persona.md"), persona);

  const voice: VoiceYaml = {
    enabled: false,
    provider: null,
    voice_id: null,
    speed: 1.0,
    pitch: 0,
    volume: 1.0,
    style: "default",
    language: "en",
  };
  writeTextFile(join(packDir, "voice.yaml"), `${toYAML(voice)}\n`);

  if (avatarMode === "live2d") {
    mkdirSync(join(packDir, "live2d", "expressions"), { recursive: true });
    mkdirSync(join(packDir, "live2d", "motions"), { recursive: true });
    writeTextFile(
      join(packDir, "live2d", "placeholder.md"),
      "# Live2D Model Placeholder\n\n" +
        "Place your Live2D model files here:\n" +
        "- `model.model3.json` — main model definition (rename from your .model3.json)\n" +
        "- `expressions/` — expression JSON files\n" +
        "- `motions/` — motion JSON files\n",
    );
  } else {
    mkdirSync(join(packDir, "vrm"), { recursive: true });
    writeTextFile(
      join(packDir, "vrm", "placeholder.md"),
      "# VRM Model Placeholder\n\n" +
        "Place your VRM model file here:\n" +
        "- `model.vrm` — VRM model file (rename to match character.yaml)\n",
    );
  }

  return packDir;
}
